# Generated by Django 5.1.4 on 2025-01-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
